import apiClient from './client';

/**
 * Invoice TypeScript Interfaces
 */

export interface Invoice {
  id: string;
  invoiceNumber: string;
  type: 'student' | 'teacher';
  recipientId: string;
  month: number;
  year: number;
  currency: string;
  totalAmount: string;
  pdfUrl: string | null;
  simplifiedPdfUrl?: string | null; // Simplified PDF for teachers (without rates)
  emailedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  recipient: {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    whatsappGroupLink?: string;
    studentCategory?: string;
    studentSubcategory?: string;
  };
  lineItems: InvoiceLineItem[];
}

export interface InvoiceLineItem {
  id: string;
  invoiceId: string;
  description: string;
  courseId: string | null;
  feeId: string | null;
  quantity: number;
  unitPrice: string;
  amount: string;
}

export interface SessionOverride {
  enrollmentId: string;
  sessionCount: number;
}

export interface OneToOneSession {
  enrollmentId: string;
  courseTitle: string;
  perSessionFee: string | null;
  currency: string;
  completedSessions: number;
  totalSessions: number;
  existingSessionCount: number | null;
}

export interface GenerateStudentInvoiceInput {
  studentId: string;
  month: number;
  year: number;
  sessionOverrides?: SessionOverride[];
}

export interface GenerateTeacherInvoiceInput {
  teacherId: string;
  month: number;
  year: number;
}

export interface GenerateMonthlyInvoicesInput {
  month: number;
  year: number;
}

export interface GenerateMonthlyStudentInvoicesResult {
  message: string;
  studentCount: number;
}

export interface GenerateMonthlyInvoicesResult {
  message: string;
  studentCount: number;
  teacherCount: number;
}

export interface GetInvoicesFilters {
  recipientId?: string;
  type?: 'student' | 'teacher';
  month?: number;
  year?: number;
  search?: string;
}

/**
 * Invoice API Methods
 */

export const invoicesApi = {
  /**
   * Get all invoices (filtered based on role)
   */
  async getInvoices(filters?: GetInvoicesFilters): Promise<Invoice[]> {
    const params = new URLSearchParams();
    if (filters?.recipientId) params.append('recipientId', filters.recipientId);
    if (filters?.type) params.append('type', filters.type);
    if (filters?.month) params.append('month', filters.month.toString());
    if (filters?.year) params.append('year', filters.year.toString());
    if (filters?.search) params.append('search', filters.search);

    const response = await apiClient.get(`/invoices?${params.toString()}`);
    return response.data.invoices;
  },

  /**
   * Get invoice by ID
   */
  async getInvoiceById(id: string): Promise<Invoice> {
    const response = await apiClient.get(`/invoices/${id}`);
    return response.data.invoice;
  },

  /**
   * Generate student invoice (admin only)
   */
  async generateStudentInvoice(input: GenerateStudentInvoiceInput): Promise<Invoice> {
    const response = await apiClient.post('/invoices/generate/student', input);
    return response.data.invoice;
  },

  /**
   * Generate teacher invoice (admin only)
   */
  async generateTeacherInvoice(input: GenerateTeacherInvoiceInput): Promise<Invoice> {
    const response = await apiClient.post('/invoices/generate/teacher', input);
    return response.data.invoice;
  },

  /**
   * Generate monthly invoices for students only (admin only)
   * Note: Teacher invoices are generated by cronjob at month end
   */
  async generateMonthlyStudentInvoices(input: GenerateMonthlyInvoicesInput): Promise<GenerateMonthlyStudentInvoicesResult> {
    const response = await apiClient.post('/invoices/generate/monthly-students', input);
    return response.data;
  },

  /**
   * Generate monthly invoices for teachers only (sudo only)
   */
  async generateMonthlyTeacherInvoices(input: GenerateMonthlyInvoicesInput): Promise<{ message: string; teacherCount: number }> {
    const response = await apiClient.post('/invoices/generate/monthly-teachers', input);
    return response.data;
  },

  /**
   * Generate monthly invoices for all students and teachers (for cronjob only)
   */
  async generateMonthlyInvoices(input: GenerateMonthlyInvoicesInput): Promise<GenerateMonthlyInvoicesResult> {
    const response = await apiClient.post('/invoices/generate/monthly', input);
    return response.data;
  },

  /**
   * Email invoice to recipient (admin only)
   */
  async emailInvoice(invoiceId: string): Promise<{ message: string }> {
    const response = await apiClient.post(`/invoices/${invoiceId}/email`);
    return response.data;
  },

  /**
   * Download invoice PDF (returns appropriate PDF based on user role)
   * Teachers get simplified PDF without rates, admins get detailed PDF
   */
  async downloadInvoice(invoiceId: string): Promise<{ pdfUrl: string; invoiceNumber: string }> {
    const response = await apiClient.get(`/invoices/${invoiceId}/download`);
    return response.data;
  },

  async get1to1Sessions(studentId: string, month: number, year: number): Promise<OneToOneSession[]> {
    const response = await apiClient.get(`/invoices/student/${studentId}/1to1-sessions?month=${month}&year=${year}`);
    return response.data.sessions;
  },
};

export default invoicesApi;
